# Generated by Django 2.2.28 on 2022-09-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_tested"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testeds",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yes", models.BigIntegerField()),
            ],
        ),
    ]
