# Generated by Django 2.2.28 on 2022-09-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testeds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testeds',
        ),
    ]
