# Generated by Django 2.2.28 on 2022-09-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_testeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='tested',
            name='yes',
            field=models.URLField(blank=True, null=True),
        ),
    ]
