# Generated by Django 2.2.28 on 2022-10-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_newmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
