# Generated by Django 2.2.28 on 2022-10-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_delete_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testhimanshu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("useradd", models.BigIntegerField()),
            ],
        ),
    ]
