# Generated by Django 2.2.28 on 2022-10-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_delete_testhimanshu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tested",
        ),
    ]
