# Generated by Django 2.2.28 on 2022-10-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_tested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testedhimanshu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BigIntegerField()),
            ],
        ),
    ]
